```{r setup, include=FALSE, results='hide'}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
source("code/populateStats.R")
source("code/calculatePeriodStats.R")
```

## Period `r currentPeriod` scores

Through games on `r as.character(lastDate)` ([website build status](https://github.com/brian-bot/pl-site/actions))

```{r leagueStats, echo=FALSE, results='asis'}
require(knitr)
options(knitr.kable.NA = "**")
teamNames <- names(allRosters[[names(currentPeriod)]])

tmpDF <- leagueStats[[ currentPeriod ]][ unlist(periods[[currentPeriod]]$matchups), ]
tmpDF$team <- paste0("[", tmpDF$team, "](./", paste0(gsub(" ", "", tolower(tmpDF$team))), ")")
kable(tmpDF, row.names = FALSE, digits=3)
```

* * *
* * *

## Season standings

```{r seasonStandings, echo=FALSE, results='asis'}
kable(standings, row.names = FALSE)
```

```{r leagueStatsFinished, echo=FALSE, results='hide'}
for(j in finishedPeriods){
  tmpDF2 <- leagueStats[[ j ]][ unlist(periods[[j]]$matchups), ]
  cat(paste0("## Period ", j, "\n\n"),
    kable(tmpDF2, row.names = FALSE, digits=3),
    "\n\n* * *\n\n",
    fill=TRUE,
    file=paste0("data/penguinRosters/", names(finishedPeriods)[j], "/FinalResults-Scores.md"))
}
```

```{r teamStats, include=FALSE, results='hide'}
for(i in teamNames){
  ## CURRENT PERIOD
  cat(paste0("## ", i, "\n\n### Batters\n\n"),
      kable(allRosters[[names(currentPeriod)]][[i]]$battingStats, row.names = FALSE, digits=3),
      "\n\n* * *\n\n### Pitchers\n\n",
      kable(allRosters[[names(currentPeriod)]][[i]]$pitchingStats, row.names = FALSE, digits=3),
      "\n\n* * *\n\n",
      fill=TRUE,
      file=paste0(gsub(" ", "", tolower(i)), ".md"))
  
  ## ALL FINISHED PERIODS
  for(j in names(finishedPeriods)){
    cat(paste0("## ", j, "\n\n## ", i, "\n\n### Batters\n\n"),
        kable(allRosters[[j]][[i]]$battingStats, row.names = FALSE, digits=3),
        "\n\n* * *\n\n### Pitchers\n\n",
        kable(allRosters[[j]][[i]]$pitchingStats, row.names = FALSE, digits=3),
        "\n\n* * *\n\n",
        fill=TRUE,
        file=paste0("data/penguinRosters/", j, "/FinalResults-", gsub(" ", "", tolower(i)), ".md"))
  }
}
```
