name: Make-PL-Website

## Run this workflow every early morning to ensure we get the past days games
on: 
  # schedule:
  #   - cron: '15 9 * * *'
  workflow_dispatch:

jobs:
  get-data:
    name: Get MLB data and build PL website
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        r-version: [4.0.4]
    
    steps:
      ## Check out a copy of this repository
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v1
        with: 
          r-version: ${{ matrix.r-version }}
      
      - name: Install libcurl
        run: |
          sudo apt-get install libcurl4-openssl-dev
          
      - name: Cache R packages
        id: cache-rpkgall8
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-rpkgall8

      - name: Install dependencies
        if: steps.cache-rpkgall8.outputs.cache-hit != 'true'
        run: |
          install.packages(c("plyr", "dplyr", "remotes", "knitr", "DT", "webshot"))
          require("remotes")
          install_github("brian-bot/mlbstats")
        shell: Rscript {0}
        
      - name: Build index.md
        run: |
          require(knitr)
          knit("buildPlSite.Rmd", "index.md")
        shell: Rscript {0}
        
      - name: Commit and push Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
